# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rU1JXIRw9HiwwTx_VwRJiJbbt7mHdhpn
"""

from collections import deque

def sliding_window_maximum(num_list, k):
    if not num_list or k == 0:
        return []

    result = []
    deque = deque()

    for i in range(len(num_list)):
        # Loại bỏ các phần tử không thuộc cửa sổ trượt
        if deque and deque[0] < i - k + 1:
            deque.popleft()

        # Loại bỏ các phần tử nhỏ hơn phần tử hiện tại từ deque
        while deque and num_list[deque[-1]] < num_list[i]:
            deque.pop()

        # Thêm phần tử hiện tại vào cuối deque
        deque.append(i)

        # Phần tử đầu tiên trong deque là giá trị lớn nhất của cửa sổ trước đó
        if i >= k - 1:
            result.append(num_list[deque[0]])

    return result

# Ví dụ:
num_list = [3, 4, 5, 1, -44, 5, 10, 12, 33, 1]
k = 3
print(sliding_window_maximum(num_list, k))